### ISSUE TITLE
Parsed input does not match actual input - extra column added

### ISSUE THREAD

**Issue by koblas** [C2FO/fast-csv#244] opened 2019-01-11 21:19 UTC
Columns that contain only a single space can generate duplicate columns in the parsed result.

```
var csv = require("fast-csv");

CSV_STRING = `bank-transfer, ,EUR,ABC`;

csv
 .fromString(CSV_STRING)
 .on("data", function(data){
     console.log(data);
 });
```

Generates the following result: ```[ 'bank-transfer', ' ', ' ', 'EUR', 'ABC' ]```

As you can see the input has 4 columns the output has 5 columns.

**Comment by SergioDonati** [comment] 2019-02-18 09:44
Same for me.
Also this row generate and extra column.
`value1,,, value4`
this generate extra column `['value1', '', '', ' ', 'value4']`

The problem is the space read as delimiter.

**Comment by SergioDonati** [comment] 2019-02-18 10:12
https://github.com/C2FO/fast-csv/blob/c1d50f8855c3636091897af6fc6eaaa1f2b07c01/lib/parser/parser.js#L127-L130

here is the problem, maybe can be avoided with strictColumnHandling option, but it's a strange behavior.

**Comment by doug-martin** [comment] 2019-07-10 20:47
This is fixed in the latest version.

```js
const CSV_STRING = 'bank-transfer, ,EUR,ABC';

csv
    .parseString(CSV_STRING)
    .on('data', data => console.log(data));
```

Output:
```
[ 'bank-transfer', ' ', 'EUR', 'ABC' ]
```

**Closed by doug-martin** 2019-07-10 20:47 UTC
